apiVersion: v1
kind: Service
metadata:
  name: webkidshop-frontend-service
  namespace: webkidshop
spec:
  selector:
    app: webkidshop-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
